#### Base Line Experiment Setup
- test pipeline performance with the base classifier on each dataset individually

In [8]:
# imports
import torch
from dataset_utils import *
from pipeline_utils.ClassificationHeads import BaselineClassificationHead
from pipeline_utils.pipeline_utils import test_classifier
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix
from pipeline_utils.pipeline_utils import train_classifier
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [9]:
def train_loop(data_loader, classifier):
    ground_truth_labels = []
    embedding_features = []
    for i, sample in enumerate(data_loader):
        ground_truth_labels.append(sample[1])
        embedding_features.append(sample[0])
        print(f"\rIteration: {i}", end="")

    # perform classification training
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(classifier.parameters(), lr=0.01)
    ground_truths, predictions = train_classifier(classifier, criterion, optimizer, embedding_features, ground_truth_labels, epochs=10)

    # performance
    print("")
    print("[training performance]")
    print("accuracy: ", accuracy_score(ground_truths, predictions))
    print("recall: ", recall_score(ground_truths, predictions, average="macro"))
    print("f1 score: ", f1_score(ground_truths, predictions, average="macro"))
    print(confusion_matrix(ground_truths, predictions))
    return predictions, ground_truths

def testing_loop(data_loader, classifier):
    ground_truth_labels = []
    embedding_features = []
    for i, sample in enumerate(data_loader):
        ground_truth_labels.append(sample[1])
        embedding_features.append(sample[0])
        print(f"\rIteration: {i}", end="")

    # perform classification training
    ground_truths, predictions = test_classifier(classifier, embedding_features, ground_truth_labels)

    # performance
    print("")
    print("[testing performance]")
    print("accuracy: ", accuracy_score(ground_truths, predictions))
    print("recall: ", recall_score(ground_truths, predictions, average="macro"))
    print("f1 score: ", f1_score(ground_truths, predictions, average="macro"))
    print(confusion_matrix(ground_truths, predictions))
    return predictions, ground_truths

In [10]:
# Dataset: Cresci-2017

# init relevant models
classifier = BaselineClassificationHead(45,6).to(device)
# train loop
dataset = ProcessedDataset("train", "../datasets/ProcessedDatasets/", "Cresci17")
train_loop(dataset, classifier)
# test loop
dataset = ProcessedDataset("test", "../datasets/ProcessedDatasets/", "Cresci17")
testing_loop(dataset, classifier)
print("--done--")

label_mapping {0: 0, 1: 1, 2: 2, 3: 3}
Iteration: 10144Epoch [1/10] - Loss: 0.4453
Epoch [2/10] - Loss: 0.2817
Epoch [3/10] - Loss: 0.2629
Epoch [4/10] - Loss: 0.2549
Epoch [5/10] - Loss: 0.2335
Epoch [6/10] - Loss: 0.2274
Epoch [7/10] - Loss: 0.2285
Epoch [8/10] - Loss: 0.2253
Epoch [9/10] - Loss: 0.2238
Epoch [10/10] - Loss: 0.2136
Loaded best model weights (Best Loss: 0.2136)

[training performance]
accuracy:  0.9239034006899951
recall:  0.918669477230219
f1 score:  0.9181348369611503
[[2321   20   19  203]
 [  32 2172   25  119]
 [  25   30 3094   44]
 [ 141   63   51 1786]]
label_mapping {0: 0, 1: 1, 2: 2, 3: 3}
Iteration: 1310
[testing performance]
accuracy:  0.7719298245614035
recall:  0.7450916766924595
f1 score:  0.7391414004459786
[[215 106   2   0]
 [  5 269   2   5]
 [  7   1 425   0]
 [  0 170   1 103]]
--done--


In [11]:
# Dataset: Cresci 2018

# init relevant models
classifier = BaselineClassificationHead(45,2).to(device)
# training loop
dataset = ProcessedDataset("train", "../datasets/ProcessedDatasets/", "Cresci18", label_mapping=[0,1])
train_loop(dataset, classifier)
# testing loop
dataset = ProcessedDataset("test", "../datasets/ProcessedDatasets/", "Cresci18", label_mapping=[0,1])
testing_loop(dataset, classifier)
print("--done--")

label_mapping {0: 0, 5: 1}
Iteration: 20834Epoch [1/10] - Loss: 0.5500
Epoch [2/10] - Loss: 0.5011
Epoch [3/10] - Loss: 0.5030
Epoch [4/10] - Loss: 0.4966
Epoch [5/10] - Loss: 0.4968
Epoch [6/10] - Loss: 0.4975
Epoch [7/10] - Loss: 0.4946
Epoch [8/10] - Loss: 0.4925
Epoch [9/10] - Loss: 0.4968
Epoch [10/10] - Loss: 0.4897
Loaded best model weights (Best Loss: 0.4897)

[training performance]
accuracy:  0.7702423806095512
recall:  0.667022257114815
f1 score:  0.6822523716737129
[[ 2542  3462]
 [ 1325 13506]]
label_mapping {0: 0, 5: 1}
Iteration: 2593
[testing performance]
accuracy:  0.8084040092521203
recall:  0.7256005939908319
f1 score:  0.7424071408890586
[[ 392  340]
 [ 157 1705]]
--done--


In [12]:
# Dataset Caverlee 11

# init relevant models
classifier = BaselineClassificationHead(45,2).to(device)
# training loop
dataset = ProcessedDataset("train", "../datasets/ProcessedDatasets/", "Caverlee11", label_mapping=[0,1])
train_loop(dataset, classifier)
# testing loop
dataset = ProcessedDataset("test", "../datasets/ProcessedDatasets/", "Caverlee11", label_mapping=[0,1])
testing_loop(dataset, classifier)
print("--done--")

label_mapping {0: 0, 4: 1}
Iteration: 31943Epoch [1/10] - Loss: 0.6258
Epoch [2/10] - Loss: 0.6012
Epoch [3/10] - Loss: 0.5963
Epoch [4/10] - Loss: 0.5958
Epoch [5/10] - Loss: 0.5953
Epoch [6/10] - Loss: 0.5941
Epoch [7/10] - Loss: 0.5915
Epoch [8/10] - Loss: 0.5936
Epoch [9/10] - Loss: 0.5923
Epoch [10/10] - Loss: 0.5920
-- stopping early --
Loaded best model weights (Best Loss: 0.5915)

[training performance]
accuracy:  0.6595917856248434
recall:  0.6602378485897913
f1 score:  0.6595461101412334
[[10350  4963]
 [ 5911 10720]]
label_mapping {0: 0, 4: 1}
Iteration: 3948
[testing performance]
accuracy:  0.7146112939984807
recall:  0.7146595153082164
f1 score:  0.7145989223367433
[[1424  541]
 [ 586 1398]]
--done--


In [13]:
# Dataset: Twibot 20
train_dataset = Twibot20("train", root="./datasets", label_mapping=[0,1])

# init relevant models
classifier = BaselineClassificationHead(45,2).to(device)
# training loop
dataset = ProcessedDataset("train", "../datasets/ProcessedDatasets/", "Twibot20", label_mapping=[0,1])
train_loop(dataset, classifier)
# testing loop
dataset = ProcessedDataset("test", "../datasets/ProcessedDatasets/", "Twibot20", label_mapping=[0,1])
testing_loop(dataset, classifier)
print("--done--")

label_mapping {0: 0, 6: 1}
Iteration: 9504Epoch [1/10] - Loss: 0.6751
Epoch [2/10] - Loss: 0.6276
Epoch [3/10] - Loss: 0.6081
Epoch [4/10] - Loss: 0.5889
Epoch [5/10] - Loss: 0.5736
Epoch [6/10] - Loss: 0.5763
Epoch [7/10] - Loss: 0.5640
Epoch [8/10] - Loss: 0.5641
Epoch [9/10] - Loss: 0.5693
Epoch [10/10] - Loss: 0.5631
Loaded best model weights (Best Loss: 0.5631)

[training performance]
accuracy:  0.7286691215149921
recall:  0.7104514357290383
f1 score:  0.7122268151943532
[[2327 1871]
 [ 708 4599]]
label_mapping {0: 0, 6: 1}
Iteration: 1148
[testing performance]
accuracy:  0.7502175805047868
recall:  0.7287213476940071
f1 score:  0.7300575881729364
[[274 236]
 [ 51 588]]
--done--


In [14]:
# Dataset: Twibot 22

# init relevant models
classifier = BaselineClassificationHead(45,2).to(device)
# training loop
ProcessedDataset("train", "../datasets/ProcessedDatasets/", "Twibot22", label_mapping=[0,1])
train_loop(dataset, classifier)
# testing loop
ProcessedDataset("test", "../datasets/ProcessedDatasets/", "Twibot22", label_mapping=[0,1])
testing_loop(dataset, classifier)
print("--done--")

label_mapping {0: 0, 6: 1}
Iteration: 1148Epoch [1/10] - Loss: 0.6924
Epoch [2/10] - Loss: 0.6676
Epoch [3/10] - Loss: 0.6444
Epoch [4/10] - Loss: 0.6461
Epoch [5/10] - Loss: 0.6489
Epoch [6/10] - Loss: 0.6147
Epoch [7/10] - Loss: 0.6036
Epoch [8/10] - Loss: 0.6064
Epoch [9/10] - Loss: 0.5951
Epoch [10/10] - Loss: 0.5924
Loaded best model weights (Best Loss: 0.5924)

[training performance]
accuracy:  0.7119234116623151
recall:  0.701615575807788
f1 score:  0.7032895532402079
[[311 199]
 [132 507]]
label_mapping {0: 0, 6: 1}
Iteration: 1148
[testing performance]
accuracy:  0.7354221061792864
recall:  0.7086900487894688
f1 score:  0.7057261477906882
[[240 270]
 [ 34 605]]
--done--
